services:
  db:
    container_name: "codeUniverseDB"
    image: postgres
    volumes:
      - "./.development/postgresql:/var/lib/postgresql:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "codeuniverse"
      POSTGRES_USER: "rt"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
  valkey:
    container_name: "codeUniverseValkey"
    image: valkey/valkey
    volumes:
      - "./.development/valkey:/data:rw"
    ports:
      - "6379:6379"
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
        - "./.development/mailpit/data:/data"
    ports:
        - "8025:8025"
        - "1025:1025"
    environment:
        MP_MAX_MESSAGES: 5000
        MP_DATABASE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
