services:
  db:
    container_name: "codeUniverseDB"
    image: postgres
    volumes:
      - "./.database/postgresql:/var/lib/postgresql:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "codeuniverse"
      POSTGRES_USER: "rt"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
